# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 21:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bikes',
            unique_together=set([('timestamp', 'place_uid', 'place_coords', 'place_name')]),
        ),
    ]
